package com.troy.qiuli.dao.mapper;

import com.troy.qiuli.dao.entity.Stock;
import com.troy.qiuli.dao.entity.StockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
* Created by Mybatis Generator 2020-09-02 09:52:05
*/
public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Sep 02 09:52:05 CST 2020
     */
    int countByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Sep 02 09:52:05 CST 2020
     */
    int deleteByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Sep 02 09:52:05 CST 2020
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Sep 02 09:52:05 CST 2020
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Sep 02 09:52:05 CST 2020
     */
    List<Stock> selectByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Sep 02 09:52:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") Stock record, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Sep 02 09:52:05 CST 2020
     */
    int updateByExample(@Param("record") Stock record, @Param("example") StockExample example);
}